### ISSUE TITLE
点击拖动不能释放问题

### ISSUE THREAD

**Issue by flyher** [district10/panorama-viewer#1]
chrome最新版

**Comment by district10** [comment]
我 Win10，Chrome 版本 56.0.2924.87 (64-bit) 没有问题哎。你是偶然这样了一次，还是总是这样？

**Comment by flyher** [comment]
复现方法。
点击->拖动->释放
重复操作，鼠标操作快点就出现了。

**Comment by district10** [comment]
回头我找个鼠标试试……或许事件响应漏掉了还是没处理掉什么的。

**Comment by district10** [comment]
试了，但没发现问题…… 🙍

**Comment by flyher** [comment]
同事复现不了，然而我在同事电脑上同样复现，Win7x64 + 最新版Chrome

**Comment by district10** [comment]
你是有神奇的手速吗……（我版本检查“Chrome 版本 56.0.2924.87 (64-bit)”已经是最新的了，我没法复现。）

**Comment by district10** [comment]
鼠标拖到其他 DOM 元素或者页面外的时候，确实有点不太符合预期。
